---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: podinfo
  namespace: wego-system
spec:
  interval: 1m0s
  path: ./gitops/flux/apps/source/podinfo
  prune: true
  sourceRef:
    kind: GitRepository
    name: podinfo

