---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: podinfo
spec:
  hostname: "podinfo.k8s.59s.io"
  acmeProvider:
    email: jmorgan@f9vs.com
---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: booksapp
spec:
  hostname: "booksapp.k8s.59s.io"
  acmeProvider:
    email: jmorgan@f9vs.com
---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: qotm
spec:
  hostname: "qotm.k8s.59s.io"
  acmeProvider:
    email: jmorgan@f9vs.com
---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: emojivoto
spec:
  hostname: "emojivoto.k8s.59s.io"
  acmeProvider:
    email: jmorgan@f9vs.com
---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: dashboard
spec:
  hostname: "dashboard.k8s.59s.io"
  acmeProvider:
    email: jmorgan@f9vs.com