---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flagger
  namespace: linkerd-viz
spec:
  timeout: 3m
  interval: 10m
  releaseName: flagger
  targetNamespace: linkerd-viz
  storageNamespace: linkerd-viz
  chart:
    spec:
      chart: flagger
      version: 1.32.0
      sourceRef:
        kind: HelmRepository
        name: flagger
        namespace: linkerd-viz
      interval: 40m
    values:
      meshProvider: linkerd
      metricsServer: http://prometheus.linkerd-viz:9090
      linkerdAuthPolicy:
        create: true
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
