---
apiVersion: getambassador.io/v3alpha1
kind: Listener
metadata:
  name: edge-stack-listener-8080
  namespace: edge-stack
spec:
  port: 8080
  protocol: HTTP
---
apiVersion: getambassador.io/v3alpha1
kind: Listener
metadata:
  name: edge-stack-listener-8443
  namespace: edge-stack
spec:
  port: 8443
  protocol: HTTPS