apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - ambassador-listener.yaml
  - https://app.getambassador.io/yaml/edge-stack/3.0.0/aes-crds.yaml
  - edge-stack.yaml

patches:
- path: namespace_patch.json
  target:
    version: v1
    kind: Namespace
    name: edge-stack
