apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ambassador.yaml
  # - ambassador-listener.yaml
  - https://app.getambassador.io/yaml/edge-stack/2.2.2/aes-crds.yaml
  - edge-stack.yaml