apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: linkerd2
    helm:
      parameters:
      - name: identity.issuer.tls.crtPEM
        value: |-
          -----BEGIN CERTIFICATE-----
          MIIBsjCCAVmgAwIBAgIRAKmitwlMPHtB26m8Hybd1AUwCgYIKoZIzj0EAwIwJTEj
          MCEGA1UEAxMacm9vdC5saW5rZXJkLmNsdXN0ZXIubG9jYWwwHhcNMjIwNzE1MTg0
          MTM4WhcNMjMwNzE1MTg0MTM4WjApMScwJQYDVQQDEx5pZGVudGl0eS5saW5rZXJk
          LmNsdXN0ZXIubG9jYWwwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAS1moOkgivQ
          ut/DiSL2srmhSaWBMNi0u3CeubNpirCS2CJi9WBxX/sBbSMVo+lDQmJVBJf+mOrj
          7oa4989UpuRfo2YwZDAOBgNVHQ8BAf8EBAMCAQYwEgYDVR0TAQH/BAgwBgEB/wIB
          ADAdBgNVHQ4EFgQUdO7DhL5wYEMC3BD7rqiREZqa8kcwHwYDVR0jBBgwFoAU9DLx
          kS4oNWX0dQycu5CxMusiNZkwCgYIKoZIzj0EAwIDRwAwRAIgQhQb1fqBsMNV63Ua
          Wjlgs/EBwDoWs2aJkI0/z+ewvMkCIEZG98bgLYou7SkScpV54fizqLU50ChGzFfg
          IcDnu78V
          -----END CERTIFICATE-----
      - name: identity.issuer.tls.keyPEM
        value: |-
          -----BEGIN EC PRIVATE KEY-----
          MHcCAQEEIEd6Cws5bzaAIO7+1EXxKTllJLzHMSx4GJiTcf5lUtSIoAoGCCqGSM49
          AwEHoUQDQgAEtZqDpIIr0Lrfw4ki9rK5oUmlgTDYtLtwnrmzaYqwktgiYvVgcV/7
          AW0jFaPpQ0JiVQSX/pjq4+6GuPfPVKbkXw==
          -----END CERTIFICATE-----
      - name: identity.issuer.tls.keyPEM
        value: |-
          -----BEGIN EC PRIVATE KEY-----
          MHcCAQEEIEd6Cws5bzaAIO7+1EXxKTllJLzHMSx4GJiTcf5lUtSIoAoGCCqGSM49
          AwEHoUQDQgAEtZqDpIIr0Lrfw4ki9rK5oUmlgTDYtLtwnrmzaYqwktgiYvVgcV/7
          AW0jFaPpQ0JiVQSX/pjq4+6GuPfPVKbkXw==
          -----END EC PRIVATE KEY-----
      - name: identityTrustAnchorsPEM
        value: |-
          -----BEGIN CERTIFICATE-----
          MIIBjjCCATOgAwIBAgIQHxSB+gBrXzoVLmQqciVLvjAKBggqhkjOPQQDAjAlMSMw
          IQYDVQQDExpyb290LmxpbmtlcmQuY2x1c3Rlci5sb2NhbDAeFw0yMjA3MTIxNjEw
          MTVaFw0zMjA3MTIwNDEwMTVaMCUxIzAhBgNVBAMTGnJvb3QubGlua2VyZC5jbHVz
          dGVyLmxvY2FsMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE2I+Ad05zcCopl7Pd
          Sb8UmKArJoryZM3i/EoABTOjm9qFV1YRL0yp6e+64/0CYXwzh63uTCoBskb3u6qD
          Qv3Ov6NFMEMwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQEwHQYD
          VR0OBBYEFPQy8ZEuKDVl9HUMnLuQsTLrIjWZMAoGCCqGSM49BAMCA0kAMEYCIQCI
          G6CJ6ZooITGfteMqcRNP1fFM3RuMCNskg3VTsgkR0AIhAInma/UrZcYl4w59uYpw
          tACxr4MRJ8o+gEmzuJK5xNY4
          -----END CERTIFICATE-----
    repoURL: https://helm.linkerd.io/stable
    targetRevision: 2.11.4
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-viz
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: linkerd-viz
    repoURL: https://helm.linkerd.io/stable
    targetRevision: 2.11.4
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
# ---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: emissary
#   namespace: argocd
# spec:
#   destination:
#     namespace: edge-stack
#     server: https://kubernetes.default.svc
#   project: default
#   source:
#     chart: edge-stack
#     repoURL: https://app.getambassador.io
#     targetRevision: 8.0.0
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#     - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ambassador-edge-stack
  namespace: argocd
spec:
  destination:
    namespace: emissary-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: gitops/argo/platform/ambassador-edge-stack
    repoURL: https://github.com/JasonMorgan/linkerd-demos
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
  namespace: argocd
spec:
  destination:
    namespace: argo-rollouts
    server: https://kubernetes.default.svc
  project: default
  source:
    path: gitops/argo/platform/argo-rollouts
    repoURL: https://github.com/JasonMorgan/linkerd-demos
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: finalizers
  namespace: argocd
spec:
  destination:
    # namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: gitops/argo/platform/finalizers
    repoURL: https://github.com/JasonMorgan/linkerd-demos
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podinfo
  namespace: argocd
spec:
  destination:
    namespace: podinfo
    server: https://kubernetes.default.svc
  project: default
  source:
    path: gitops/argo/apps/podinfo
    repoURL: https://github.com/JasonMorgan/linkerd-demos
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true