apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  timeout: 3m
  interval: 40m
  releaseName: cert-manager
  targetNamespace: cert-manager
  storageNamespace: cert-manager
  chart:
    spec:
      chart: cert-manager
      version: v1.12.3
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: cert-manager
      interval: 40m
  values:
    installCRDs: true
  postRenderers:
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace


