apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  timeout: 3m
  interval: 40m
  releaseName: cert-manager
  targetNamespace: cert-manager
  storageNamespace: cert-manager
  chart:
    spec:
      chart: cert-manager
      version: v1.8.0
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: cert-manager
      interval: 40m
  values:
    installCRDs: true
  postRenderers:
    - kustomize:
        patchesStrategicMerge:
          - kind: Deployment
            apiVersion: apps/v1
            metadata:
              name: cert-manager-webhook
              namespace: cert-manager
            spec:
              template:
                metadata:
                  annotations:
                    linkerd.io/inject: enabled
          - kind: Deployment
            apiVersion: apps/v1
            metadata:
              name: cert-manager
              namespace: cert-manager
            spec:
              template:
                metadata:
                  annotations:
                    linkerd.io/inject: enabled
          - kind: Deployment
            apiVersion: apps/v1
            metadata:
              name: cert-manager-cainjector
              namespace: cert-manager
            spec:
              template:
                metadata:
                  annotations:
                    linkerd.io/inject: enabled
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace


