---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: linkerd
  namespace: linkerd
spec:
  interval: 2m
  url: oci://buoyant.azurecr.io/helm/
  type: "oci"
  secretRef:
    name: buoyant-acr-secret