---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd-crds
  namespace: linkerd
spec:
  timeout: 3m
  interval: 10m
  releaseName: linkerd-crds
  targetNamespace: linkerd
  storageNamespace: linkerd
  chart:
    spec:
      chart: linkerd-crds
      version: 1.6.1
      sourceRef:
        kind: HelmRepository
        name: linkerd
        namespace: linkerd
      interval: 40m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
---
kind: Namespace
apiVersion: v1
metadata:
  name: linkerd
  labels:
    linkerd.io/is-control-plane: "true"
    config.linkerd.io/admission-webhooks: disabled
    linkerd.io/control-plane-ns: linkerd