---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: emojivoto
  namespace: emojivoto
spec:
  prefix: /
  service: web-svc.emojivoto:80
  rewrite: ""
  host: emojivoto.civo.59s.io