---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: linkerd-demos
  namespace: wego-system
spec:
  interval: 1m0s
  path: ./gitops/flux/runtime/manifests
  prune: true
  sourceRef:
    kind: GitRepository
    name: linkerd-demos

