apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd-buoyant
  namespace: buoyant-cloud
spec:
  timeout: 3m
  interval: 10m
  releaseName: linkerd-buoyant
  targetNamespace: buoyant-cloud
  storageNamespace: buoyant-cloud
  chart:
    spec:
      chart: linkerd-buoyant
      version: 1.9.5
      sourceRef:
        kind: HelmRepository
        name: linkerd
        namespace: linkerd
      interval: 40m
  values:
    installNamespace: false
  valuesFrom:
    
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
