namespace: podinfo
bases:
  - github.com/stefanprodan/podinfo/kustomize/?ref=5.1.3

resources:
  - frontend.yaml
  - ns.yaml
  # - ingress.yaml
  - generator.yaml
  # - canary.yaml
  - mapping.yaml

patchesStrategicMerge:
  - patch.yaml