---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: podinfo
spec:
  prefix: /
  service: podinfo.podinfo:9898
  rewrite: ""
---
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: podinfo
spec:
  hostname: "podinfo.59s.io"
  acmeProvider:
    email: jmorgan@f9vs.com