apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: podinfod
          securityContext:
            runAsUser: 1337
          env:
          - name: PODINFO_UI_COLOR
            value: '#008000' # #008000 #1919FF
---
apiVersion: v1
kind: Service
metadata:
  name: podinfo
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: podinfo
