apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: podinfod
          securityContext:
            runAsUser: 1337
          env:
          - name: PODINFO_UI_COLOR
            value: '#008000' # #008000 #1919FF
          # - name: PODINFO_UI_MESSAGE
          #   value: 'Hello from Version 2!'
---
apiVersion: v1
kind: Service
metadata:
  name: podinfo
  labels:
    # mirror.linkerd.io/exported: "true"


