apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: frontdoor
  namespace: nginx-ingress
spec:
  timeout: 3m
  interval: 40m
  releaseName: nginx-ingress-controller
  targetNamespace: nginx-ingress
  storageNamespace: nginx-ingress
  chart:
    spec:
      chart: nginx-ingress
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: nginx-ingress
      interval: 40m
  postRenderers:
    - kustomize:
        patchesStrategicMerge:
          - kind: Deployment
            apiVersion: apps/v1
            metadata:
              name: frontdoor-nginx-ingress-controller
              namespace: nginx-ingress
            spec:
              template:
                metadata:
                  annotations:
                    linkerd.io/inject: enabled
  values:
    installNamespace: false
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: nginx-ingress
spec:
  interval: 2m
  url: https://charts.bitnami.com/bitnami
---
kind: Namespace
apiVersion: v1
metadata:
  name: nginx-ingress