apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: dashboard
  namespace: default
spec:
  prefix: /
  service: web.linkerd-viz:8084
  host_rewrite: web.linkerd-viz.svc.cluster.local:8084
  rewrite: ""
  hostname: dashboard.civo.59s.io
  allow_upgrade:
  - websocket
  remove_request_headers:
  - Origin
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: argocd-server-ui
  namespace: argocd
spec:
  hostname: argocd.civo.59s.io
  prefix: /
  service: argocd-server:443
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: argocd-server-cli
  namespace: argocd
spec:
  # NOTE: the port must be ignored if you have strip_matching_host_port enabled on envoy
  hostname: argocd.civo.59s.io:443
  prefix: /
  service: argocd-server:80
  regex_headers:
    Content-Type: "^application/grpc.*$"
  grpc: true