apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: dashboard
  namespace: linkerd-viz
spec:
  hostname: dashboard.civo.59s.io
  acmeProvider:
    email: jmorgan@f9vs.com
  # tlsSecret:
  #   name: wildcard
---
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: emojivoto
  namespace: emojivoto
spec:
  hostname: emojivoto.civo.59s.io
  acmeProvider:
    email: jmorgan@f9vs.com
---
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: podinfo
  namespace: podinfo
spec:
  hostname: podinfo.civo.59s.io
  acmeProvider:
    email: jmorgan@f9vs.com
---
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: booksapp
  namespace: booksapp
spec:
  hostname: booksapp.civo.59s.io
  acmeProvider:
    email: jmorgan@f9vs.com
---
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: wildcard
  namespace: default
spec:
  hostname: "*"
  requestPolicy:
    insecure:
      action: Reject
