apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: dashboard
  namespace: emissary
spec:
  hostname: "dashboard.civo.59s.io"
  acmeProvider:
    email: jmorgan@f9vs.com
  tlsSecret:
    name: linkerd-dashboard