apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: dashboard
  namespace: default
spec:
  hostname: "dashboard.k8s.59s.io"
  acmeProvider:
    email: jmorgan@f9vs.com
  tlsSecret:
    name: wildcard
