apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: dashboard
  namespace: emissary
spec:
  prefix: /
  service: web.linkerd-viz:8084
  host_rewrite: web.linkerd-viz.svc.cluster.local:8084
  rewrite: ""
  host: dashboard.civo.59s.io
  allow_upgrade:
  - websocket
  remove_request_headers:
  - Origin
