---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: ambassador
  namespace: flux-system
spec:
  interval: 47h59m28s
 #suspend: true
  path: 
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: ingress-nginx
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: ambassador
      namespace: ambassador
---
kind: Namespace
apiVersion: v1
metadata:
  name: ambassador
  