apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ambassador-edge-stack
  namespace: flux-system
spec:
  timeout: 3m
  interval: 40m
  releaseName: ambassador-edge-stack
  targetNamespace: ambassador
  storageNamespace: ambassador
  chart:
    spec:
      chart: ambassador
      sourceRef:
        kind: HelmRepository
        name: ambassador
        namespace: flux-system
      interval: 40m
  postRenderers:
    - kustomize:
        patchesStrategicMerge:
          - kind: Deployment
            apiVersion: apps/v1
            metadata:
              name: ambassador
              namespace: ambassador
              annotations:
                config.linkerd.io/skip-inbound-ports: 80,443
                linkerd.io/inject: enabled
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace