apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ambassador-edge-stack
  namespace: ambassador
spec:
  timeout: 3m
  interval: 40m
  releaseName: ambassador
  targetNamespace: ambassador
  storageNamespace: ambassador
  chart:
    spec:
      chart: edge-stack
      version: 8.7.2
      sourceRef:
        kind: HelmRepository
        name: ambassador
        namespace: ambassador
      interval: 40m
  values:
    emissary-ingress:
      replicaCount: 1
      podAnnotations:
        linkerd.io/inject: enabled
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
