---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: linkerd-viz
spec:
  prefix: /
  # host: linkerd.59s.io
  host_rewrite: web.linkerd-viz.svc.cluster.local:8084
  service: web.linkerd-viz.svc.cluster.local:8084
  rewrite: ""
  allow_upgrade:
  - websocket
