apiVersion: v1
kind: Namespace
metadata:
  name: qotm
  annotations:
    linkerd.io/inject: enabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qotm
  namespace: qotm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qotm
  template:
    metadata:
      labels:
        app: qotm
    spec:
      containers:
      - name: qotm
        image: docker.io/datawire/qotm:1.7
        ports:
        - name: http-api
          containerPort: 5000
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 60
          periodSeconds: 3
        resources:
          limits:
            cpu: "0.1"
            memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: qotm-linkerd2
  namespace: qotm
spec:
  ports:
  - name: http
    port: 80
    targetPort: 5000
  selector:
    app: qotm
---
