---
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: podinfo
  namespace: podinfo
spec:
  hostname: podinfo.civo.59s.io
  acmeProvider:
    email: jmorgan@f9vs.com
  tlsSecret:
    name: podinfo