apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: emissary
  namespace: emissary
spec:
  timeout: 3m
  interval: 40m
  releaseName: emissary
  targetNamespace: emissary
  storageNamespace: emissary
  chart:
    spec:
      chart: emissary-ingress
      sourceRef:
        kind: HelmRepository
        name: emissary
        namespace: emissary
      interval: 40m
  postRenderers:
    - kustomize:
        patchesStrategicMerge:
          - kind: Deployment
            apiVersion: apps/v1
            metadata:
              name: emissary-emissary-ingress
              namespace: emissary
            spec:
              template:
                metadata:
                  annotations:
                    config.linkerd.io/skip-inbound-ports: 80,443
                    linkerd.io/inject: enabled
          - kind: Deployment
            apiVersion: apps/v1
            metadata:
              name: emissary-emissary-ingress-agent
              namespace: emissary
            spec:
              template:
                metadata:
                  annotations:
                    linkerd.io/inject: enabled
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
