apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: emissary-edge-stack
  namespace: emissary-ingress
spec:
  timeout: 3m
  interval: 40m
  releaseName: emissary
  targetNamespace: emissary-ingress
  storageNamespace: emissary-ingress
  chart:
    spec:
      chart: edge-stack
      sourceRef:
        kind: HelmRepository
        name: emissary
        namespace: emissary-ingress
      interval: 40m
  postRenderers:
    - kustomize:
        patchesStrategicMerge:
          - kind: Deployment
            apiVersion: apps/v1
            metadata:
              name: emissary-ingress
              namespace: emissary-ingress
            spec:
              template:
                metadata:
                  annotations:
                    config.linkerd.io/skip-inbound-ports: 80,443
                    linkerd.io/inject: enabled
          # - kind: Deployment
          #   apiVersion: apps/v1
          #   metadata:
          #     name: ambassador-agent
          #     namespace: emissary-ingress
          #   spec:
          #     template:
          #       metadata:
          #         annotations:
          #           linkerd.io/inject: enabled
          # - kind: Deployment
          #   apiVersion: apps/v1
          #   metadata:
          #     name: ambassador-redis
          #     namespace: emissary-ingress
            # spec:
            #   template:
            #     metadata:
            #       annotations:
            #         config.linkerd.io/skip-inbound-ports: 80,443
            #         linkerd.io/inject: enabled
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
