---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./gitops/flux/runtime/source/cert-manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops
  validation: client
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: cert-manager
      namespace: cert-manager
    - apiVersion: cert-manager.io/v1
      kind: Certificate
      name: linkerd-identity-issuer
      namespace: linkerd
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: linkerd
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./gitops/flux/runtime/source/linkerd
  dependsOn:
    - name: cert-manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops
  validation: client
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: linkerd-control-plane
      namespace: linkerd
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: linkerd-crds
      namespace: linkerd
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: linkerd-viz
  namespace: flux-system
spec:
  dependsOn:
  - name: linkerd
  interval: 1m0s
  path: ./gitops/flux/runtime/source/linkerd-viz
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops
  validation: client
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: linkerd-viz
      namespace: linkerd-viz
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
# kind: Kustomization
# metadata:
#   name: nginx-ingress
#   namespace: flux-system
# spec:
#   dependsOn:
#   - name: linkerd-viz
#   interval: 1m0s
#   path: ./gitops/flux/runtime/source/nginx-ingress
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: gitops
#   validation: client
#   healthChecks:
#     - apiVersion: helm.toolkit.fluxcd.io/v2beta1
#       kind: HelmRelease
#       name: frontdoor
#       namespace: nginx-ingress
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: emissary
  namespace: flux-system
spec:
  dependsOn:
  - name: linkerd-viz
  interval: 3m0s
  path: ./gitops/flux/runtime/source/emissary
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops
  validation: client
  healthChecks:
    - kind: Deployment
      name: emissary-apiext
      namespace: emissary-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: ambassador
  namespace: flux-system
spec:
  dependsOn:
  - name: linkerd-viz
  - name: emissary
  interval: 3m0s
  path: ./gitops/flux/runtime/source/ambassador
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops
  validation: client
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: ambassador-edge-stack
      namespace: edge-stack
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: flagger
  namespace: flux-system
spec:
  dependsOn:
  - name: linkerd-viz
  interval: 1m0s
  path: ./gitops/flux/runtime/source/flagger
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops
  validation: client
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: flagger
      namespace: linkerd-viz
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: linkerd-multicluster
  namespace: flux-system
spec:
  dependsOn:
  - name: linkerd-viz
  interval: 1m0s
  path: ./gitops/flux/runtime/source/linkerd-multicluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops
  validation: client
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: linkerd-multicluster
      namespace: linkerd-multicluster
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: finalizers
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./gitops/flux/runtime/source/finalizers
  dependsOn:
    - name: flagger
    - name: linkerd-viz
    - name: ambassador
    # - name: nginx-ingress
    - name: cert-manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops
  validation: client