---
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: booksapp
  namespace: default
spec:
  hostname: "booksapp.civo.59s.io"
  acmeProvider:
    email: jmorgan@f9vs.com
  # tlsSecret:
  #   name: wildcard