apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: booksapp
  namespace: booksapp
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/service-upstream: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
  - host: booksapp.civo.59s.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: webapp
            port:
              number: 7000
  tls:
  - hosts:
    - booksapp.civo.59s.io
    secretName: booksapp-ingress