apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: booksapp
  namespace: booksapp
  annotations:
    nginx.ingress.kubernetes.io/service-upstream: true
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: webapp
            port:
              number: 7000