apiVersion: split.smi-spec.io/v1alpha2
kind: TrafficSplit
metadata:
    name: emoji-svc
    namespace: emojivoto
    annotations:
        failover.linkerd.io/primary-service: emoji-svc
    labels:
        failover.linkerd.io/controlled-by: linkerd-failover
spec:
    service: emoji-svc
    backends:
        - service: emoji-svc
          weight: 1
        - service: emoji-svc-prod2
          weight: 0
