# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
# kind: Kustomization
# metadata:
#   name: podinfo
#   namespace: flux-system
# spec:
#   interval: 1m0s
#   path: ./gitops/flux/apps/source/podinfo
#   dependsOn:
#     - name: finalizers
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: gitops
#   validation: client
#   healthChecks:
#     - apiVersion: apps/v1
#       kind: Deployment
#       name: podinfo
#       namespace: podinfo
#     - apiVersion: apps/v1
#       kind: Deployment
#       name: generator
#       namespace: podinfo
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: emojivoto
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./gitops/flux/apps/source/emojivoto
  dependsOn:
    - name: finalizers
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops
  validation: client
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: emoji
      namespace: emojivoto
    - apiVersion: apps/v1
      kind: Deployment
      name: vote-bot
      namespace: emojivoto
    - apiVersion: apps/v1
      kind: Deployment
      name: web
      namespace: emojivoto
    - apiVersion: apps/v1
      kind: Deployment
      name: voting
      namespace: emojivoto
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: booksapp
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./gitops/flux/apps/source/booksapp
  dependsOn:
    - name: finalizers
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops
  validation: client
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: traffic
      namespace: booksapp
    - apiVersion: apps/v1
      kind: Deployment
      name: webapp
      namespace: booksapp
    - apiVersion: apps/v1
      kind: Deployment
      name: authors
      namespace: booksapp
    - apiVersion: apps/v1
      kind: Deployment
      name: books
      namespace: booksapp
