---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./gitops/flux/apps/source/podinfo
  dependsOn:
    - name: flagger
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops
  validation: client
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: podinfo
      namespace: podinfo
    - apiVersion: apps/v1
      kind: Deployment
      name: generator
      namespace: podinfo
    - apiVersion: apps/v1
      kind: Deployment
      name: frontend
      namespace: podinfo
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./gitops/flux/apps/source/podinfo
  dependsOn:
    - name: flagger
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops
  validation: client
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: podinfo
      namespace: podinfo
    - apiVersion: apps/v1
      kind: Deployment
      name: generator
      namespace: podinfo
    - apiVersion: apps/v1
      kind: Deployment
      name: frontend
      namespace: podinfo
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./gitops/flux/apps/source/podinfo
  dependsOn:
    - name: flagger
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops
  validation: client
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: podinfo
      namespace: podinfo
    - apiVersion: apps/v1
      kind: Deployment
      name: generator
      namespace: podinfo
    - apiVersion: apps/v1
      kind: Deployment
      name: frontend
      namespace: podinfo
