---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./podinfo
  prune: true
  sourceRef:
    kind: GitRepository
    name: apps
  validation: client